
// This file is auto-generated. Do not edit manually.
export const migrationData: { [key: string]: string } = {
  "meta/_journal.json": "{\n  \"version\": \"7\",\n  \"dialect\": \"sqlite\",\n  \"entries\": [\n    {\n      \"idx\": 0,\n      \"version\": \"6\",\n      \"when\": 1751933028499,\n      \"tag\": \"0000_needy_sersi\",\n      \"breakpoints\": true\n    },\n    {\n      \"idx\": 1,\n      \"version\": \"6\",\n      \"when\": 1753848150397,\n      \"tag\": \"0001_foamy_glorian\",\n      \"breakpoints\": true\n    },\n    {\n      \"idx\": 2,\n      \"version\": \"6\",\n      \"when\": 1753904120281,\n      \"tag\": \"0002_far_whirlwind\",\n      \"breakpoints\": true\n    }\n  ]\n}",
  "meta/0000_snapshot.json": "{\n  \"version\": \"6\",\n  \"dialect\": \"sqlite\",\n  \"id\": \"bf0d3f75-6d97-4a9d-b105-8052c6303306\",\n  \"prevId\": \"00000000-0000-0000-0000-000000000000\",\n  \"tables\": {\n    \"accounts\": {\n      \"name\": \"accounts\",\n      \"columns\": {\n        \"account\": {\n          \"name\": \"account\",\n          \"type\": \"text\",\n          \"primaryKey\": true,\n          \"notNull\": true,\n          \"autoincrement\": false\n        },\n        \"min_ms\": {\n          \"name\": \"min_ms\",\n          \"type\": \"integer\",\n          \"primaryKey\": false,\n          \"notNull\": true,\n          \"autoincrement\": false\n        },\n        \"min_kb\": {\n          \"name\": \"min_kb\",\n          \"type\": \"integer\",\n          \"primaryKey\": false,\n          \"notNull\": true,\n          \"autoincrement\": false\n        },\n        \"inc_ms\": {\n          \"name\": \"inc_ms\",\n          \"type\": \"integer\",\n          \"primaryKey\": false,\n          \"notNull\": true,\n          \"autoincrement\": false\n        },\n        \"inc_kb\": {\n          \"name\": \"inc_kb\",\n          \"type\": \"integer\",\n          \"primaryKey\": false,\n          \"notNull\": true,\n          \"autoincrement\": false\n        },\n        \"max_fee\": {\n          \"name\": \"max_fee\",\n          \"type\": \"text\",\n          \"primaryKey\": false,\n          \"notNull\": true,\n          \"autoincrement\": false\n        }\n      },\n      \"indexes\": {},\n      \"foreignKeys\": {},\n      \"compositePrimaryKeys\": {},\n      \"uniqueConstraints\": {},\n      \"checkConstraints\": {}\n    }\n  },\n  \"views\": {},\n  \"enums\": {},\n  \"_meta\": {\n    \"schemas\": {},\n    \"tables\": {},\n    \"columns\": {}\n  },\n  \"internal\": {\n    \"indexes\": {}\n  }\n}",
  "0000_needy_sersi.sql": "CREATE TABLE `accounts` (\n\t`account` text PRIMARY KEY NOT NULL,\n\t`min_ms` integer NOT NULL,\n\t`min_kb` integer NOT NULL,\n\t`inc_ms` integer NOT NULL,\n\t`inc_kb` integer NOT NULL,\n\t`max_fee` text NOT NULL\n);\n",
  "0001_foamy_glorian.sql": "CREATE TABLE `contracts` (\n\t`contract` text PRIMARY KEY NOT NULL,\n\t`abi` text NOT NULL\n);\n",
  "0002_far_whirlwind.sql": "CREATE TABLE `manager` (\n\t`account` text PRIMARY KEY NOT NULL,\n\t`permission` text NOT NULL,\n\t`key` text NOT NULL\n);\n"
};
