declare module 'bun' {
	interface Env {
		ANTELOPE_CHAIN_ID: string;
		ANTELOPE_NODEOS_API: string;
		ANTELOPE_SYSTEM_TOKEN: string;
		MANAGER_ACCOUNT_NAME: string;
		MANAGER_ACCOUNT_PERMISSION: string;
		MANAGER_ACCOUNT_PRIVATEKEY: string;
		PROVIDER_ACCOUNT_NAME: string;
		PROVIDER_ACCOUNT_PERMISSION: string;
		PROVIDER_ACCOUNT_PRIVATEKEY: string;
		PROVIDER_FREE_POWERUP_MAX_PAYMENT: number;
	}
}
