name: Code Checks

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: cp .env.example .env
      - run: make check
