name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: |
          set -ex
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            bun build --target=bun-windows-x64 --compile --minify --sourcemap src/index.ts --outfile dist/rpcli-windows-x64
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            bun build --target=bun-darwin-x64 --compile --minify --sourcemap src/index.ts --outfile dist/rpcli-darwin-x64
          else
            bun build --target=bun-linux-x64 --compile --minify --sourcemap src/index.ts --outfile dist/rpcli-linux-x64
          fi
        shell: bash

      - name: Prepare release assets
        run: |
          set -ex
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv dist/rpcli-windows-x64 dist/rpcli.exe
            7z a "rpcli-${{ github.ref_name }}-${{ matrix.os }}.zip" "./dist/rpcli.exe"
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            mv dist/rpcli-darwin-x64 dist/rpcli
            tar -czvf "rpcli-${{ github.ref_name }}-${{ matrix.os }}.tar.gz" -C ./dist rpcli
          else
            mv dist/rpcli-linux-x64 dist/rpcli
            tar -czvf "rpcli-${{ github.ref_name }}-${{ matrix.os }}.tar.gz" -C ./dist rpcli
          fi
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rpcli-*.tar.gz
            rpcli-*.zip
